name: Eden Acoustique
favicon: null
layout_spectrum: 0.32204
typography_spectrum: 0.49123
title: Eden Acoustique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2d30'
    - '#000000'
    - '#d3d1d6'
    - '#ffffff'
    - '#716b6a'
  brandStrength: 0.7835693089291453
  lightness: 0.9839298294391483
  saturation: 0.33812190731987357
  rhythmicContrast: 0.732091658981517
purpose: []
