name: Eden Acoustique
favicon: null
layout_spectrum: 0.6351
typography_spectrum: 0.49123
title: Eden Acoustique
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#b6b5ba'
    - '#050304'
    - '#2c2a30'
    - '#6b5c5a'
  brandStrength: 0.7835693089291453
  lightness: 0.9839298294391483
  saturation: 0.33812190731987357
  rhythmicContrast: 0.732091658981517
purpose: []
