typography_spectrum: 0.49123
color:
  brandColors:
    - '#070707'
    - '#ffffff'
    - '#9d9a93'
    - '#3d2410'
    - '#cfcbc0'
  brandStrength: 0.7835693089291453
  lightness: 0.9839298294391483
  saturation: 0.33812190731987357
  rhythmicContrast: 0.732091658981517
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50294
analytics:
  google: null
  facebook: null
  twitter: null
name: Eden Acoustique
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Eden Acoustique
description: The Sound of Art
purpose: []
